version: '3'
services:
  mongodb:
    image: mongo
    container_name: my-mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
    networks:
      - my-network
  ticket_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ticket-service
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    environment:
      DB_PASSWORD: admin_password
      DB_USER: admin
      DB_PORT: 27017
    networks:
      - my-network
volumes:
  mongodb-data:
networks:
  my-network: