# Utiliza una imagen oficial de Node.js como base
FROM node:14-alpine

# Establece el directorio de trabajo en /usr/src/app
WORKDIR /usr/src/app

# Copia los archivos de la aplicación
COPY . .

# Instala las dependencias, incluido nodemon globalmente
RUN npm install -g nodemon && npm install

# Expone el puerto 3000 para la aplicación
EXPOSE 3000

# Comando para iniciar la aplicación con nodemon
CMD ["nodemon", "app.js"]
